language: php

sudo: false

matrix:
    include:
        - php: 7.0
        - php: 7.1
        - php: 7.2
          env: deps=low
    fast_finish: true

install:
    - phpenv config-rm xdebug.ini
    - if [[ $deps = low ]]; then composer update --prefer-lowest --prefer-stable; else composer install; fi

script:
    - phpdbg -qrr vendor/bin/phpunit --coverage-text

notifications:
    email: false
